apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stage-randomquotes-java
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    name: 'stage'
    namespace: default
  source:
    path: out-stage/
    repoURL: 'https://github.com/fdaluisio/RandomQuotes-Java-infra.git'
    targetRevision: HEAD
  syncPolicy: {}
