apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stage-randomquotes-java
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    name: 'stage'
    namespace: default
      #    server: 'https://192.168.11.167:6445'
  source:
    path: randomquotes-java
    repoURL: 'https://github.com/fdaluisio/RandomQuotes-Java-infra.git'
    targetRevision: HEAD
    helm:
      valueFiles:
        - values-stage.yaml
      releaseName: stage-argocd-randomquotes-java
  syncPolicy: {}
#    syncOptions:
#      - CreateNamespace=true
#    automated:
#      selfHeal: true
#      prune: true
#      allowEmpty: true
