apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-randomquotes-java
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    name: 'dev'
    namespace: default
  source:
    path: out-dev/
    repoURL: 'https://github.com/fdaluisio/RandomQuotes-Java-infra.git'
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
      allowEmpty: true
