apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: randomquotes-java-prod
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    name: ''
    namespace: prod
    server: 'https://kubernetes.default.svc'
  source:
    path: randomquotes-java
    repoURL: 'https://github.com/fdaluisio/RandomQuotes-Java-infra.git'
    targetRevision: HEAD
    helm:
      valueFiles:
        - values-prod.yaml
      releaseName: argocd-randomquotes-java-stage
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
      allowEmpty: true
